name: Release

on:
  release:
    types:
      - published

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build and Test
        run: dotnet test /p:Configuration=Release --verbosity normal
      - name: Pack
        run: dotnet pack /p:Configuration=Release /p:Version=${GITHUB_REF#refs/tags/} --no-build --verbosity normal
      - name: Publish NuGets (if this version not published before)
        run: dotnet nuget push **\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN_2022 }} --skip-duplicate
